### ISSUE TITLE
Load static files 

### ISSUE THREAD

**Issue by ZechCodes** [beginner-codes/summer-of-code-website#27]
We need to be able to load static files (JavaScript, CSS, etc.). These files should be located in the `static` folder at the root of the project. 

[Here's the docs for serving static files with FastAPI](https://fastapi.tiangolo.com/tutorial/static-files/)

- [x] #33
- [x] #32
- [x] #29
- [x] #30
- [x] #31

**Comment by aryan-debug** [comment]
May I do it?
